apiVersion: v2
name: cloudrun-service
description: Templates a Google Cloud Run Service YAML manifest that can be
  deployed using the Google Cloud CLI.
type: application
version: 1.0.0
maintainers:
  - name: 'Michael Reichenbach (Silthus)'
    email: 'me@silthus.net'
    url: 'https://github.com/silthus'
